# Generated by Django 5.2.7 on 2026-09-23 23:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def create_private_memberships(apps, schema_editor):
    Conversation = apps.get_model("chat", "Conversation")
    Membership = apps.get_model("chat", "ConversationMembership")
    rows = []
    for conversation in Conversation.objects.iterator():
        rows.extend(
            (
                Membership(conversation_id=conversation.pk, user_id=conversation.user_low_id, role="member"),
                Membership(conversation_id=conversation.pk, user_id=conversation.user_high_id, role="member"),
            )
        )
    Membership.objects.bulk_create(rows, ignore_conflicts=True)


def remove_private_memberships(apps, schema_editor):
    apps.get_model("chat", "ConversationMembership").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Propriétaire'), ('admin', 'Administrateur'), ('member', 'Membre')], default='member', max_length=12)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('joined_after_message_id', models.BigIntegerField(default=0)),
                ('left_after_message_id', models.BigIntegerField(blank=True, null=True)),
                ('muted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('declined', 'Refusée'), ('cancelled', 'Annulée'), ('expired', 'Expirée')], db_index=True, default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.RemoveConstraint(
            model_name='conversation',
            name='unique_private_pair',
        ),
        migrations.RemoveConstraint(
            model_name='conversation',
            name='private_pair_ordered_distinct',
        ),
        migrations.AddField(
            model_name='conversation',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='conversation',
            name='kind',
            field=models.CharField(choices=[('private', 'Privée'), ('group', 'Groupe')], db_index=True, default='private', max_length=12),
        ),
        migrations.AddField(
            model_name='conversation',
            name='name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='conversation',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='groups_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='user_high',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_high', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='user_low',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_low', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'private')), fields=('user_low', 'user_high'), name='unique_private_pair'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'private'), ('owner__isnull', True), ('user_high__isnull', False), ('user_low__isnull', False)), models.Q(('kind', 'group'), ('owner__isnull', False), ('user_high__isnull', True), ('user_low__isnull', True)), _connector='OR'), name='conversation_kind_shape'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.CheckConstraint(condition=models.Q(('kind', 'group'), ('user_low_id__lt', models.F('user_high_id')), _connector='OR'), name='private_pair_ordered_distinct'),
        ),
        migrations.AddField(
            model_name='conversationmembership',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='chat.conversation'),
        ),
        migrations.AddField(
            model_name='conversationmembership',
            name='last_read_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chat.message'),
        ),
        migrations.AddField(
            model_name='conversationmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupinvitation',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='chat.conversation'),
        ),
        migrations.AddField(
            model_name='groupinvitation',
            name='invitee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_invitations_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupinvitation',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_invitations_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(create_private_memberships, remove_private_memberships),
        migrations.AddIndex(
            model_name='conversationmembership',
            index=models.Index(fields=['user', 'left_at'], name='chat_member_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversationmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('left_at__isnull', True)), fields=('conversation', 'user'), name='unique_active_membership'),
        ),
        migrations.AddConstraint(
            model_name='conversationmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('left_at__isnull', True), ('role', 'owner')), fields=('conversation',), name='unique_active_group_owner'),
        ),
        migrations.AddConstraint(
            model_name='groupinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('conversation', 'invitee'), name='unique_pending_group_invite'),
        ),
    ]
