# Generated by Django 5.1.7 on 2026-09-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='coach_messages',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='lesson',
            name='hints',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='active_lines',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='current_fen',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='current_ply',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='hint_stage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='last_feedback',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
