import { FormEvent, ReactNode, useEffect, useRef, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Link, Navigate, Route, Routes, useLocation, useNavigate, useParams } from 'react-router-dom'
import { api, errorText } from './api'
import type { Conversation, Message, MessagePage, User } from './types'

const initials = (name:string) => name.trim().split(/\s+/).slice(0,2).map(x=>x[0]?.toUpperCase()).join('') || '?'
const time = (value:string) => new Intl.DateTimeFormat('fr',{hour:'2-digit',minute:'2-digit'}).format(new Date(value))

function Logo({compact=false}:{compact?:boolean}) {
  return <div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-brand-500 shadow-lg shadow-brand-500/20" aria-hidden><svg viewBox="0 0 24 24" className="h-6 w-6 fill-white"><path d="M4 4h16v11a3 3 0 0 1-3 3h-6l-5 3 1-3a3 3 0 0 1-3-3V4Zm4 5h8V7H8v2Zm0 4h6v-2H8v2Z"/></svg></span>{!compact&&<span><b className="block text-xl tracking-tight">Table Chat</b><small className="text-slate-500">Prototype privé</small></span>}</div>
}

function Loading() { return <main className="grid min-h-dvh place-items-center bg-slate-50"><div className="text-center"><Logo/><div className="mx-auto mt-8 h-1.5 w-28 overflow-hidden rounded bg-slate-200"><div className="h-full w-1/2 animate-pulse rounded bg-brand-500"/></div></div></main> }

function useMe() {
  return useQuery({queryKey:['me'],queryFn:()=>api<User>('/me/'),retry:false})
}

function Protected({children}:{children:ReactNode}) {
  const me=useMe(); const location=useLocation()
  if(me.isLoading) return <Loading/>
  if(me.isError) return <Navigate to="/login" replace state={{from:location.pathname}}/>
  return children
}

function AuthPage({mode}:{mode:'login'|'register'}) {
  const navigate=useNavigate(); const qc=useQueryClient(); const [error,setError]=useState('')
  const [fields,setFields]=useState({email:'',public_id:'',display_name:'',password:''})
  const mutation=useMutation({mutationFn:()=>api<User>(`/auth/${mode}/`,{method:'POST',body:JSON.stringify(fields)}),onSuccess:user=>{qc.setQueryData(['me'],user);navigate('/chats',{replace:true})},onError:e=>setError(errorText(e))})
  const submit=(e:FormEvent)=>{e.preventDefault();setError('');mutation.mutate()}
  return <main className="min-h-dvh bg-[radial-gradient(circle_at_top_left,#d8efff,transparent_45%),linear-gradient(135deg,#f8fbfe,#e9f3fb)] px-5 py-8 sm:grid sm:place-items-center">
    <div className="mx-auto grid w-full max-w-5xl overflow-hidden rounded-[2rem] bg-white shadow-soft lg:grid-cols-[1.05fr_.95fr]">
      <section className="relative hidden min-h-[650px] overflow-hidden bg-brand-600 p-12 text-white lg:flex lg:flex-col lg:justify-between">
        <div className="absolute -right-20 -top-20 h-72 w-72 rounded-full border-[45px] border-white/10"/><div className="absolute -bottom-12 left-16 h-52 w-52 rounded-full bg-white/10"/>
        <Logo/><div className="relative"><p className="mb-4 text-sm font-semibold uppercase tracking-[.2em] text-blue-100">Simple. Direct. Durable.</p><h1 className="max-w-md text-5xl font-bold leading-tight">Les conversations qui comptent, à votre table.</h1><p className="mt-6 max-w-md text-lg leading-relaxed text-blue-100">Échangez des messages privés en temps réel, sur téléphone comme sur ordinateur.</p></div><p className="relative text-sm text-blue-100">Version d’essai privée · Messages lisibles par le serveur</p>
      </section>
      <section className="p-7 sm:p-12 lg:p-14"><div className="mb-10 lg:hidden"><Logo/></div><p className="text-sm font-bold text-brand-600">{mode==='login'?'BON RETOUR':'BIENVENUE'}</p><h2 className="mt-2 text-3xl font-bold tracking-tight text-slate-900">{mode==='login'?'Connectez-vous':'Créez votre compte'}</h2><p className="mt-3 text-slate-500">{mode==='login'?'Retrouvez vos conversations là où vous les avez laissées.':'Quelques informations suffisent pour commencer.'}</p>
        <form onSubmit={submit} className="mt-9 space-y-5">
          <Field label="Adresse email" type="email" autoComplete="email" value={fields.email} onChange={email=>setFields({...fields,email})}/>
          {mode==='register'&&<><Field label="Identifiant public" hint="3–32 caractères : lettres, chiffres, point, tiret ou _" autoComplete="username" value={fields.public_id} onChange={public_id=>setFields({...fields,public_id:public_id.toLowerCase()})}/><Field label="Nom affiché" autoComplete="name" value={fields.display_name} onChange={display_name=>setFields({...fields,display_name})}/></>}
          <Field label="Mot de passe" type="password" autoComplete={mode==='login'?'current-password':'new-password'} hint={mode==='register'?'10 caractères minimum':''} value={fields.password} onChange={password=>setFields({...fields,password})}/>
          {error&&<div role="alert" className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
          <button disabled={mutation.isPending} className="min-h-12 w-full rounded-xl bg-brand-500 px-5 font-semibold text-white shadow-lg shadow-brand-500/20 transition hover:bg-brand-600 disabled:opacity-60">{mutation.isPending?'Patientez…':mode==='login'?'Se connecter':'Créer mon compte'}</button>
        </form><p className="mt-7 text-center text-sm text-slate-500">{mode==='login'?'Pas encore de compte ?':'Déjà un compte ?'} <Link className="font-semibold text-brand-600 hover:underline" to={mode==='login'?'/register':'/login'}>{mode==='login'?'S’inscrire':'Se connecter'}</Link></p>
      </section>
    </div>
  </main>
}

function Field({label,hint,onChange,...props}:{label:string;hint?:string;onChange:(v:string)=>void}&Omit<React.InputHTMLAttributes<HTMLInputElement>,'onChange'>) { return <label className="block"><span className="mb-2 block text-sm font-semibold text-slate-700">{label}</span><input required onChange={e=>onChange(e.target.value)} {...props} className="min-h-12 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 text-slate-900 transition placeholder:text-slate-400 focus:border-brand-500 focus:bg-white focus:outline-none"/>{hint&&<small className="mt-1.5 block text-slate-400">{hint}</small>}</label> }

type IconName='chats'|'calls'|'games'|'settings'|'search'|'send'|'back'|'edit'|'logout'
function Icon({name,className='h-5 w-5'}:{name:IconName;className?:string}) { const paths:Record<IconName,string>={chats:'M21 12a8 8 0 0 1-8 8H7l-4 2 1.3-3.9A8 8 0 1 1 21 12Z',calls:'M7 3H4a1 1 0 0 0-1 1c0 9.4 7.6 17 17 17a1 1 0 0 0 1-1v-3l-4-1-1 2c-4.2-1.3-6.7-3.8-8-8l2-1-1-4-2-2Z',games:'M8 7h8a5 5 0 0 1 4.7 6.7l-1.3 3.8a2 2 0 0 1-3.2.8L14 16h-4l-2.2 2.3a2 2 0 0 1-3.2-.8l-1.3-3.8A5 5 0 0 1 8 7Zm0 3v4m-2-2h4m6-1h.01M18 14h.01',settings:'M12 15.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7Zm0-12 1 2.1 2.3.6 2-1.2 1.7 1.7-1.2 2 .6 2.3 2.1 1v2.4l-2.1 1-.6 2.3 1.2 2-1.7 1.7-2-1.2-2.3.6-1 2.1H9.6l-1-2.1-2.3-.6-2 1.2-1.7-1.7 1.2-2-.6-2.3-2.1-1V11l2.1-1 .6-2.3-1.2-2L4.3 4l2 1.2 2.3-.6 1-2.1H12Z',search:'m21 21-4.4-4.4m2.4-5.1a7.5 7.5 0 1 1-15 0 7.5 7.5 0 0 1 15 0Z',send:'m22 2-7 20-4-9-9-4 20-7Zm-11 11L22 2',back:'m15 18-6-6 6-6',edit:'M13.5 6.5 17.5 10.5M4 20l4.5-1 10-10a2.8 2.8 0 0 0-4-4l-10 10L4 20Z',logout:'M10 17l5-5-5-5m5 5H3m10-9h6a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-6'}; return <svg aria-hidden viewBox="0 0 24 24" className={className} fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d={paths[name]}/></svg> }

const nav=[{to:'/chats',label:'Discussions',icon:'chats' as const},{to:'/calls',label:'Appels',icon:'calls' as const},{to:'/games',label:'Jeux',icon:'games' as const},{to:'/settings',label:'Réglages',icon:'settings' as const}]
function BottomNav() { const loc=useLocation(); return <nav aria-label="Navigation principale" className="safe-bottom grid grid-cols-4 border-t border-slate-200 bg-white px-1 pt-2 md:hidden">{nav.map(item=>{const active=loc.pathname.startsWith(item.to);return <Link key={item.to} to={item.to} className={`flex min-h-14 flex-col items-center justify-center gap-1 rounded-xl text-[11px] font-semibold ${active?'text-brand-600':'text-slate-400'}`}><Icon name={item.icon}/><span>{item.label}</span></Link>})}</nav> }

function DesktopNav() { const loc=useLocation(); return <aside className="hidden w-[88px] shrink-0 flex-col items-center border-r border-slate-200 bg-white py-5 md:flex"><Logo compact/><nav aria-label="Navigation principale" className="mt-12 flex w-full flex-col gap-3 px-3">{nav.map(item=>{const active=loc.pathname.startsWith(item.to);return <Link title={item.label} aria-label={item.label} key={item.to} to={item.to} className={`grid h-14 place-items-center rounded-2xl ${active?'bg-brand-50 text-brand-600':'text-slate-400 hover:bg-slate-50'}`}><Icon name={item.icon} className="h-6 w-6"/></Link>})}</nav></aside> }

function AppFrame({children}:{children:ReactNode}) { return <main className="flex h-dvh overflow-hidden bg-slate-100"><DesktopNav/><div className="flex min-w-0 flex-1 flex-col">{children}<BottomNav/></div></main> }

function ConversationList({activeId}:{activeId?:string}) { const navigate=useNavigate(); const [searchOpen,setSearchOpen]=useState(false); const query=useQuery({queryKey:['conversations'],queryFn:()=>api<Conversation[]>('/conversations/')})
  return <section className={`${activeId?'hidden md:flex':'flex'} w-full shrink-0 flex-col border-r border-slate-200 bg-white md:w-[360px] lg:w-[400px]`}><header className="flex h-20 items-center justify-between px-5"><div><h1 className="text-2xl font-bold tracking-tight">Discussions</h1><p className="text-xs text-slate-400">Vos messages privés</p></div><button onClick={()=>setSearchOpen(true)} aria-label="Rechercher un contact" className="grid h-11 w-11 place-items-center rounded-xl bg-brand-50 text-brand-600 hover:bg-brand-100"><Icon name="edit"/></button></header><div className="px-4 pb-3"><button onClick={()=>setSearchOpen(true)} className="flex min-h-11 w-full items-center gap-3 rounded-xl bg-slate-100 px-4 text-sm text-slate-400"><Icon name="search"/>Rechercher un identifiant</button></div><div className="flex-1 overflow-y-auto px-2 pb-3">{query.isLoading&&<p className="p-6 text-center text-sm text-slate-400">Chargement…</p>}{query.data?.length===0&&<EmptyChats onStart={()=>setSearchOpen(true)}/>} {query.data?.map(c=><button key={c.id} onClick={()=>navigate(`/chats/${c.id}`)} className={`flex w-full gap-3 rounded-2xl p-3 text-left transition ${activeId===c.id?'bg-brand-50':'hover:bg-slate-50'}`}><Avatar user={c.other_user}/><span className="min-w-0 flex-1"><span className="flex items-center justify-between gap-2"><b className="truncate text-[15px]">{c.other_user.display_name}</b><small className="shrink-0 text-slate-400">{c.last_message?time(c.last_message.created_at):''}</small></span><span className="mt-1 block truncate text-sm text-slate-500">{c.last_message?.content || `@${c.other_user.public_id}`}</span></span></button>)}</div>{searchOpen&&<ContactSearch onClose={()=>setSearchOpen(false)}/>}</section> }

function Avatar({user,size='normal'}:{user:User;size?:'normal'|'large'}) { return <span aria-hidden className={`grid shrink-0 place-items-center rounded-full bg-gradient-to-br from-brand-500 to-cyan-400 font-bold text-white shadow-sm ${size==='large'?'h-24 w-24 text-2xl':'h-12 w-12'}`}>{initials(user.display_name)}</span> }
function EmptyChats({onStart}:{onStart:()=>void}) { return <div className="mx-4 mt-16 text-center"><div className="mx-auto grid h-20 w-20 place-items-center rounded-full bg-brand-50 text-brand-500"><Icon name="chats" className="h-9 w-9"/></div><h2 className="mt-5 font-bold">Votre table est prête</h2><p className="mt-2 text-sm leading-relaxed text-slate-500">Recherchez un proche par son identifiant public pour démarrer.</p><button onClick={onStart} className="mt-5 rounded-xl bg-brand-500 px-5 py-3 text-sm font-semibold text-white">Trouver un contact</button></div> }

function ContactSearch({onClose}:{onClose:()=>void}) { const [term,setTerm]=useState(''); const navigate=useNavigate(); const query=useQuery({queryKey:['user-search',term],queryFn:()=>api<User[]>(`/users/search/?public_id=${encodeURIComponent(term)}`),enabled:term.length>=3,retry:false}); const create=useMutation({mutationFn:(publicId:string)=>api<Conversation>('/conversations/',{method:'POST',body:JSON.stringify({contact_public_id:publicId})}),onSuccess:c=>{onClose();navigate(`/chats/${c.id}`)}})
 return <div role="dialog" aria-modal="true" aria-labelledby="search-title" className="fixed inset-0 z-30 flex items-start justify-center bg-slate-900/35 p-4 pt-[10vh] backdrop-blur-sm"><div className="w-full max-w-md rounded-3xl bg-white p-5 shadow-2xl"><div className="flex items-center justify-between"><h2 id="search-title" className="text-xl font-bold">Nouvelle discussion</h2><button onClick={onClose} aria-label="Fermer" className="h-10 w-10 rounded-full text-2xl text-slate-400 hover:bg-slate-100">×</button></div><label className="mt-5 flex min-h-12 items-center gap-3 rounded-xl border border-slate-200 bg-slate-50 px-4 focus-within:border-brand-500"><Icon name="search" className="h-5 w-5 text-slate-400"/><span className="sr-only">Identifiant public exact</span><input autoFocus value={term} onChange={e=>setTerm(e.target.value.toLowerCase().trim())} placeholder="identifiant exact" className="min-w-0 flex-1 bg-transparent outline-none"/></label><p className="mt-2 text-xs text-slate-400">La recherche porte uniquement sur l’identifiant public exact.</p><div className="mt-4 min-h-24">{query.isFetching&&<p className="p-4 text-sm text-slate-400">Recherche…</p>}{term.length>=3&&query.data?.length===0&&<p className="p-4 text-sm text-slate-500">Aucun contact trouvé.</p>}{query.data?.map(user=><button key={user.id} disabled={create.isPending} onClick={()=>create.mutate(user.public_id)} className="flex w-full items-center gap-3 rounded-2xl p-3 text-left hover:bg-slate-50"><Avatar user={user}/><span><b className="block">{user.display_name}</b><small className="text-slate-500">@{user.public_id}</small></span></button>)}</div>{create.isError&&<p role="alert" className="text-sm text-red-600">{errorText(create.error)}</p>}</div></div> }

function ChatsPage() { const {conversationId}=useParams(); return <AppFrame><div className="flex min-h-0 flex-1"><ConversationList activeId={conversationId}/>{conversationId?<Chat conversationId={conversationId}/>:<WelcomePane/>}</div></AppFrame> }
function WelcomePane() { return <section className="chat-pattern hidden flex-1 place-items-center md:grid"><div className="max-w-sm text-center"><div className="mx-auto grid h-24 w-24 place-items-center rounded-[2rem] bg-white text-brand-500 shadow-soft"><Icon name="chats" className="h-11 w-11"/></div><h2 className="mt-7 text-2xl font-bold">Bienvenue sur Table Chat</h2><p className="mt-3 leading-relaxed text-slate-500">Choisissez une discussion ou retrouvez un contact pour commencer à échanger.</p><span className="mt-5 inline-flex rounded-full bg-white px-4 py-2 text-xs text-slate-400 shadow-sm">Prototype pour essais privés</span></div></section> }

function mergeMessages(current:Message[], incoming:Message) { const filtered=current.filter(m=>m.id!==incoming.id&&m.client_id!==incoming.client_id); return [...filtered,{...incoming,status:'saved' as const}].sort((a,b)=>(a.server_sequence||Number.MAX_SAFE_INTEGER)-(b.server_sequence||Number.MAX_SAFE_INTEGER)) }
function mergeBatch(current:Message[], incoming:Message[]) { return incoming.reduce(mergeMessages,current) }

function Chat({conversationId}:{conversationId:string}) { const navigate=useNavigate(); const qc=useQueryClient(); const me=useMe(); const details=useQuery({queryKey:['conversation',conversationId],queryFn:()=>api<Conversation>(`/conversations/${conversationId}/`)}); const history=useQuery({queryKey:['messages',conversationId],queryFn:()=>api<MessagePage>(`/conversations/${conversationId}/messages/`)}); const [messages,setMessages]=useState<Message[]>([]); const messagesRef=useRef<Message[]>([]); const [olderCursor,setOlderCursor]=useState<number|null>(null); const [loadingOlder,setLoadingOlder]=useState(false); const [draft,setDraft]=useState(''); const [socketState,setSocketState]=useState<'connecting'|'live'|'offline'>('connecting'); const listRef=useRef<HTMLDivElement>(null)
 useEffect(()=>{messagesRef.current=messages},[messages])
 useEffect(()=>{if(history.data){const initial=history.data.results.map(m=>({...m,status:'saved' as const}));messagesRef.current=initial;setMessages(initial);setOlderCursor(history.data.next_before)}},[history.data,conversationId])
 useEffect(()=>{if(!history.isSuccess)return;let socket:WebSocket|undefined;let retry:number|undefined;let ping:number|undefined;let stopped=false;let attempt=0; const catchUp=async()=>{let after=messagesRef.current.reduce((n,m)=>Math.max(n,m.server_sequence||0),0);try{for(let batch=0;batch<100;batch++){const page=await api<MessagePage>(`/conversations/${conversationId}/messages/?after=${after}`);if(!page.results.length)break;setMessages(cur=>mergeBatch(cur,page.results));after=Math.max(...page.results.map(m=>m.server_sequence));if(page.results.length<100)break}}catch{/* La reconnexion suivante reprendra le rattrapage. */}}; const connect=()=>{setSocketState('connecting');const scheme=location.protocol==='https:'?'wss':'ws';socket=new WebSocket(`${scheme}://${location.host}/ws/conversations/${conversationId}/`);socket.onopen=async()=>{attempt=0;setSocketState('live');await catchUp();ping=window.setInterval(()=>socket?.readyState===1&&socket.send(JSON.stringify({type:'ping'})),20000)};socket.onmessage=e=>{const event=JSON.parse(e.data);if(event.type==='message.created'){setMessages(cur=>mergeMessages(cur,event.message));qc.invalidateQueries({queryKey:['conversations']})}};socket.onclose=e=>{clearInterval(ping);if(e.code===4401){qc.removeQueries({queryKey:['me']});navigate('/login',{replace:true});return}setSocketState('offline');if(!stopped){const delay=Math.min(30000,1000*2**attempt++)+Math.random()*500;retry=window.setTimeout(connect,delay)}}};connect();const online=()=>{if(socket?.readyState!==WebSocket.OPEN){clearTimeout(retry);connect()}};window.addEventListener('online',online);return()=>{stopped=true;clearTimeout(retry);clearInterval(ping);socket?.close();window.removeEventListener('online',online)}},[conversationId,history.isSuccess,navigate,qc])
 useEffect(()=>{requestAnimationFrame(()=>listRef.current?.scrollTo({top:listRef.current.scrollHeight,behavior:'smooth'}))},[messages.length])
 const send=async(content:string,clientId:string=crypto.randomUUID())=>{const pending:Message={id:-Date.now(),server_sequence:0,conversation_id:conversationId,author_id:me.data!.id,client_id:clientId,content,created_at:new Date().toISOString(),status:'pending'};setMessages(cur=>[...cur.filter(m=>m.client_id!==clientId),pending]);setDraft('');try{const saved=await api<Message>(`/conversations/${conversationId}/messages/`,{method:'POST',body:JSON.stringify({client_id:clientId,content})});setMessages(cur=>mergeMessages(cur,saved));qc.invalidateQueries({queryKey:['conversations']})}catch{setMessages(cur=>cur.map(m=>m.client_id===clientId?{...m,status:'failed'}:m))}}
 const submit=(e:FormEvent)=>{e.preventDefault();const content=draft.trim();if(content)void send(content)}
 if(details.isLoading||history.isLoading)return <section className="grid flex-1 place-items-center bg-slate-50 text-slate-400">Chargement de la discussion…</section>
 if(details.isError)return <section className="grid flex-1 place-items-center bg-slate-50 p-6 text-center"><div><p className="font-semibold text-red-600">Discussion inaccessible.</p><button onClick={()=>navigate('/chats')} className="mt-4 text-brand-600">Retour</button></div></section>
 const contact=details.data!.other_user
 const loadOlder=async()=>{if(!olderCursor||loadingOlder)return;setLoadingOlder(true);try{const page=await api<MessagePage>(`/conversations/${conversationId}/messages/?before=${olderCursor}`);setMessages(cur=>mergeBatch(page.results,cur));setOlderCursor(page.next_before)}finally{setLoadingOlder(false)}}
 return <section className="flex min-w-0 flex-1 flex-col bg-white"><header className="flex h-20 shrink-0 items-center gap-3 border-b border-slate-200 bg-white px-3 sm:px-5"><button onClick={()=>navigate('/chats')} className="grid h-10 w-10 place-items-center rounded-xl text-slate-500 md:hidden" aria-label="Retour aux discussions"><Icon name="back"/></button><Avatar user={contact}/><div className="min-w-0 flex-1"><h1 className="truncate font-bold">{contact.display_name}</h1><p className={`text-xs ${socketState==='live'?'text-emerald-600':'text-slate-400'}`}>{socketState==='live'?'Connecté':socketState==='connecting'?'Connexion…':'Hors ligne — reconnexion automatique'}</p></div></header><div ref={listRef} aria-live="polite" className="chat-pattern flex-1 overflow-y-auto px-3 py-5 sm:px-6"><div className="mx-auto flex max-w-3xl flex-col gap-2">{olderCursor&&<button onClick={loadOlder} disabled={loadingOlder} className="mb-3 self-center rounded-full bg-white px-4 py-2 text-xs font-semibold text-brand-600 shadow-sm">{loadingOlder?'Chargement…':'Afficher les messages précédents'}</button>}{messages.length===0&&<div className="my-8 self-center rounded-full bg-white/90 px-4 py-2 text-xs text-slate-500 shadow-sm">Début de votre conversation avec {contact.display_name}</div>}{messages.map(message=><MessageBubble key={`${message.client_id}-${message.id}`} message={message} mine={message.author_id===me.data!.id} retry={()=>send(message.content,message.client_id)}/>)}</div></div><form onSubmit={submit} className="safe-bottom flex shrink-0 items-end gap-2 border-t border-slate-200 bg-white p-3 sm:px-6"><label className="min-w-0 flex-1"><span className="sr-only">Votre message</span><textarea value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();if(draft.trim())void send(draft.trim())}}} maxLength={4000} rows={1} placeholder="Votre message…" className="max-h-32 min-h-12 w-full resize-none rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 outline-none focus:border-brand-500 focus:bg-white"/></label><button disabled={!draft.trim()} aria-label="Envoyer" className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-brand-500 text-white shadow-md shadow-brand-500/20 disabled:bg-slate-200 disabled:shadow-none"><Icon name="send"/></button></form></section> }

function MessageBubble({message,mine,retry}:{message:Message;mine:boolean;retry:()=>void}) { return <div className={`max-w-[86%] ${mine?'self-end':'self-start'}`}><div className={`rounded-2xl px-4 py-2.5 shadow-sm ${mine?'rounded-br-md bg-brand-500 text-white':'rounded-bl-md bg-white text-slate-800'}`}><p className="whitespace-pre-wrap break-words text-[15px] leading-relaxed">{message.content}</p><div className={`mt-1 flex items-center justify-end gap-1.5 text-[10px] ${mine?'text-blue-100':'text-slate-400'}`}><time>{time(message.created_at)}</time>{mine&&<span>{message.status==='pending'?'En attente':message.status==='failed'?'Échec':'Enregistré'}</span>}</div></div>{message.status==='failed'&&<button onClick={retry} className="mt-1 text-xs font-semibold text-red-600 hover:underline">Réessayer</button>}</div> }

function Unavailable({kind}:{kind:'Appels'|'Jeux'}) { return <AppFrame><section className="grid flex-1 place-items-center p-8 text-center"><div className="max-w-md"><div className="mx-auto grid h-24 w-24 place-items-center rounded-[2rem] bg-white text-brand-500 shadow-soft"><Icon name={kind==='Appels'?'calls':'games'} className="h-11 w-11"/></div><span className="mt-7 inline-block rounded-full bg-amber-100 px-3 py-1 text-xs font-bold text-amber-700">BIENTÔT DISPONIBLE</span><h1 className="mt-4 text-3xl font-bold">{kind}</h1><p className="mt-3 leading-relaxed text-slate-500">Cette fonctionnalité ne fait pas partie du prototype actuel. Aucun appel ni jeu fictif n’est simulé.</p></div></section></AppFrame> }

function Settings() { const me=useMe(); const qc=useQueryClient(); const navigate=useNavigate(); const [name,setName]=useState('');const [bio,setBio]=useState('');const [message,setMessage]=useState('');useEffect(()=>{if(me.data){setName(me.data.display_name);setBio(me.data.bio)}},[me.data]);const save=useMutation({mutationFn:()=>api<User>('/me/',{method:'PATCH',body:JSON.stringify({display_name:name,bio})}),onSuccess:user=>{qc.setQueryData(['me'],user);setMessage('Profil enregistré.')},onError:e=>setMessage(errorText(e))});const logout=async()=>{await api('/auth/logout/',{method:'POST'});qc.clear();navigate('/login',{replace:true})};if(!me.data)return null;return <AppFrame><section className="flex-1 overflow-y-auto p-4 sm:p-8"><div className="mx-auto max-w-2xl"><h1 className="text-3xl font-bold">Réglages</h1><div className="mt-7 rounded-3xl bg-white p-6 shadow-sm sm:p-8"><div className="flex flex-col items-center border-b border-slate-100 pb-7 text-center"><Avatar user={{...me.data,display_name:name||me.data.display_name}} size="large"/><h2 className="mt-4 text-xl font-bold">{me.data.display_name}</h2><p className="text-sm text-slate-500">@{me.data.public_id}</p></div><form onSubmit={e=>{e.preventDefault();setMessage('');save.mutate()}} className="mt-7 space-y-5"><Field label="Nom affiché" value={name} onChange={setName}/><label className="block"><span className="mb-2 block text-sm font-semibold">Courte présentation</span><textarea maxLength={160} rows={3} value={bio} onChange={e=>setBio(e.target.value)} className="w-full resize-none rounded-xl border border-slate-200 bg-slate-50 p-4 outline-none focus:border-brand-500"/></label><div><span className="block text-sm font-semibold">Adresse email</span><p className="mt-2 text-sm text-slate-500">{me.data.email} <span className="ml-2 rounded bg-slate-100 px-2 py-1 text-[10px]">privée</span></p></div>{message&&<p role="status" className="text-sm text-slate-600">{message}</p>}<button disabled={save.isPending} className="rounded-xl bg-brand-500 px-5 py-3 font-semibold text-white">Enregistrer</button></form></div><div className="mt-4 rounded-3xl border border-red-100 bg-white p-6"><button onClick={logout} className="flex items-center gap-3 font-semibold text-red-600"><Icon name="logout"/>Se déconnecter</button></div><p className="mt-5 px-2 text-xs leading-relaxed text-slate-400">Prototype pour essais privés : pas de vérification d’email ni de récupération de mot de passe. Les messages ne sont pas chiffrés de bout en bout et restent lisibles par le serveur.</p></div></section></AppFrame> }

export default function App() { return <Routes><Route path="/login" element={<AuthPage mode="login"/>}/><Route path="/register" element={<AuthPage mode="register"/>}/><Route path="/chats" element={<Protected><ChatsPage/></Protected>}/><Route path="/chats/:conversationId" element={<Protected><ChatsPage/></Protected>}/><Route path="/calls" element={<Protected><Unavailable kind="Appels"/></Protected>}/><Route path="/games" element={<Protected><Unavailable kind="Jeux"/></Protected>}/><Route path="/settings" element={<Protected><Settings/></Protected>}/><Route path="*" element={<Navigate to="/chats" replace/>}/></Routes> }
